### PR TITLE
Implementation of SDBlock.num_atoms for issue #18

### PR DESCRIPTION
**Pull request by coleb**
Takes care of the sublty between V2000 and V3000. This also provides
some V3000 test cases as well.

### CODE REVIEW

**Comment by coleb** [comment]
@pechersky, merge conflicts resolved, fixed up pre-commit, so I think this is ok to merge. Let me know of any other changes needed.

**Comment by pechersky** [comment]
It's not OK to merge, because here is how a V2000 counts line looks like with 999 atoms:
```
999998  0  0  0  0  0  0  0  0999 V2000
```
So `split` gives you 999998 atoms.

**Comment by coleb** [comment]
Note, the V2000 code branch uses a fixed width of 3 to parse the number of atoms: 
https://github.com/coleb/sendoff/blob/b349a8c49f7209c895c9bed826676e3ccab40979/sendoff/sdblock.py#L146 


```python

        frmt = self.mdl[2].strip()
        if frmt.endswith("V2000"):
            return int(frmt[:3])
        elif frmt.endswith("V3000"):
```

V3000 switched from fixed width columns to space separated. This is why V3000 supports over 999 atoms. 

There is also a test case to explicit test the 999 atom case, in both V2000 and V3000: https://github.com/coleb/sendoff/blob/b349a8c49f7209c895c9bed826676e3ccab40979/tests/fixtures.py#L86

```python
def test_999_atom_mol(tmp_path: Path) -> Path:
    """Write two molecules with 999 atoms to V2000 and V3000.
    Args:
        tmp_path: pytest fixture for writing files to a temp directory
    Returns:
        Path to the sdf
    """
    mol = Chem.MolFromSmiles("C" * 999)
    outpath = tmp_path / "input.sdf"
    with Chem.SDWriter(str(outpath)) as sdw:
        sdw.write(mol)
        sdw.SetForceV3000(True)
        sdw.write(mol)
    return outpath
```

**Comment by pechersky** [comment]
Closed by #22.

**Pull request closed without merging**
